# gNMIC Configuration for Arista EOS

username: netadmin
timeout: 10s

common_eos_subscriptions: &common_eos_subs
  skip-verify: true
  insecure: true
  password: netadmin
  encoding: json_ietf
  subscriptions:
    - interface-stats
    - system-info
    - bgp-sessions

targets:
  cfsa-cnt1-0001:
      address: cfsa-cnt1-0001:6030
      <<: *common_eos_subs
  cfsa-cnt1-0002:
      address: cfsa-cnt1-0002:6030
      <<: *common_eos_subs
  cfsa-cnt1-0201a:
      address: cfsa-cnt1-0201a:6030
      <<: *common_eos_subs
  cfsa-cnt1-0201b:
      address: cfsa-cnt1-0201b:6030
      <<: *common_eos_subs
  #cfsa-cnt1-0202a:
      #address: cfsa-cnt1-0202a:6030
      #<<: *common_eos_subs
  #cfsa-cnt1-0202b:
      #address: cfsa-cnt1-0202b:6030
      #<<: *common_eos_subs

subscriptions:
  # Interface Statistics (OpenConfig Path)
  interface-stats:
    paths:
      - /interfaces/interface/state/counters
    mode: stream
    stream-mode: sample
    sample-interval: 10s

  # System Information (OpenConfig Path)
  system-info:
    paths:
      - /system/state
    mode: stream
    stream-mode: sample
    sample-interval: 60s

  # BGP Sessions (OpenConfig Path)
  bgp-sessions:
    paths:
      - /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state
    mode: stream
    stream-mode: on-change

outputs:
  prom-output:
    type: prometheus
    listen: :9273
    metric-prefix: gnmic
    append-subscription-name: true
    strings-as-labels: true
    export-timestamps: true
    debug: false
