# gNMIC Configuration for Arista EOS

username: netadmin
timeout: 10s

common_eos_subscriptions: &common_eos_subs
  skip-verify: true
  insecure: false
  password: netadmin
  subscriptions:
    - interface-stats
    - system-info
    - bgp-sessions

targets:
  cfsa-cnt1-0001:
      address: cfsa-cnt1-0001:6030
      <<: *common_eos_subs
  cfsa-cnt1-0002:
      address: cfsa-cnt1-0002:6030
      <<: *common_eos_subs
  cfsa-cnt1-0201a:
      address: cfsa-cnt1-0201a:6030
      <<: *common_eos_subs
  cfsa-cnt1-0201b:
      address: cfsa-cnt1-0201b:6030
      <<: *common_eos_subs
  #cfsa-cnt1-0202a:
      #address: cfsa-cnt1-0202a:6030
      #<<: *common_eos_subs
  #cfsa-cnt1-0202b:
      #address: cfsa-cnt1-0202b:6030
      #<<: *common_eos_subs

subscriptions:
  # Interface Statistics (OpenConfig Path)
  interface-stats:
    paths:
      - /interfaces/interface/state/counters
    mode: stream
    stream-mode: sample
    sample-interval: 10s
    encoding: proto

  # System Information (OpenConfig Path)
  system-info:
    paths:
      - /system/state
    mode: stream
    stream-mode: sample
    sample-interval: 60s
    encoding: proto

  # BGP Sessions (OpenConfig Path)
  bgp-sessions:
    paths:
      - /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state
    mode: stream
    stream-mode: on-change
    encoding: proto

outputs:
  output1:
    type: prometheus # Or influxdb/loki depending on your specific lab setup
    listen-address: :9804
    path: /metrics
    add-target-label: true